from py_news.reason_codes import (
    AUTH_INVALID_OR_MISSING,
    AUTH_NOT_CONFIGURED,
    ALL_REASON_CODES,
    ARTICLE_NOT_FOUND,
    CONTENT_MISSING_LOCAL,
    DIRECT_URL_NOT_ALLOWED,
    EMPTY_BODY,
    HTTP_FAILURE,
    LOCAL_CONTENT_HIT,
    LOCAL_METADATA_HIT,
    METADATA_REFRESHED,
    NON_HTML_RESPONSE,
    NO_MATCH,
    NOT_FOUND,
    PARSE_FAILURE,
    STRATEGY_NOT_SUPPORTED,
    STRATEGY_NOT_SUPPORTED_FOR_PROVIDER,
    SUCCESS,
)


def test_required_operator_reason_codes_present():
    required = {
        LOCAL_METADATA_HIT,
        LOCAL_CONTENT_HIT,
        METADATA_REFRESHED,
        CONTENT_MISSING_LOCAL,
        ARTICLE_NOT_FOUND,
        NO_MATCH,
        NOT_FOUND,
        STRATEGY_NOT_SUPPORTED,
        STRATEGY_NOT_SUPPORTED_FOR_PROVIDER,
        DIRECT_URL_NOT_ALLOWED,
        HTTP_FAILURE,
        NON_HTML_RESPONSE,
        EMPTY_BODY,
        PARSE_FAILURE,
        SUCCESS,
        AUTH_NOT_CONFIGURED,
        AUTH_INVALID_OR_MISSING,
    }
    assert required.issubset(ALL_REASON_CODES)
